name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    permissions:
      contents: read

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - run: dotnet build
